deploy:
  provider: pages
  skip-cleanup: true
  github-token: a29acec57a510e4c0eab1d54d803551992dd6053  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
after_success:
  - chmod 777 deploy.sh
  - ./deploy.sh


